# Generated by Django 3.2 on 2023-01-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_not_me'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='not_me',
        ),
    ]
