# Generated by Django 3.2 on 2023-01-27 13:36

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230126_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid Email'), django.core.validators.MaxLengthValidator(limit_value=254)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=150, unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=150), django.contrib.auth.validators.UnicodeUsernameValidator()]),
            preserve_default=False,
        ),
    ]
