# Generated by Django 3.2 on 2023-02-19 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Значение должно быть от 1 до 10'), django.core.validators.MaxValueValidator(10, message='Значение должно быть от 1 до 10')], verbose_name='Оценка'),
        ),
    ]
