# Generated by Django 3.2 on 2023-02-21 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Значение должно быть не менее 1'), django.core.validators.MaxValueValidator(10, message='Значение должно быть не более 10')], verbose_name='Оценка'),
        ),
    ]
